services:
  ros1:
    build: ../ubuntu20_ros1
    image: ros1-noetic-local
    container_name: ros1_container
    stdin_open: true   # -i
    tty: true          # -t
    network_mode: host
    hostname: ros1-noetic
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - ROS_MASTER_URI=http://localhost:11311
      - TZ=Asia/Seoul
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/jisang/docker_ws/shared_workspace:/workspace
      - /home/jisang/docker_ws/git:/git
      - /home/jisang/Dataset:/dataset:ro
      - /home/jisang/git/02_project/T-Car_ADS/src/rte/msg:/msg_src:ro
      - /home/jisang/docker_ws/ubuntu20_ros1/.bashrc_ros1:/root/.bashrc
    working_dir: /
    command: bash
