services:
  ros2:
    image: osrf/ros:humble-desktop-full
    container_name: ros2_container
    stdin_open: true   # -i
    tty: true          # -t
    network_mode: host
    hostname: ros2-humble
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/jisang/docker_ws/shared_workspace:/workspace
      - /home/jisang/docker_ws/git:/git
      - /home/jisang/docker_ws/ubuntu22_ros2/.bashrc_ros2:/root/.bashrc
    working_dir: /
    command: bash
